site_name: ITDpy
site_description: Python SDK for ИТД.com API 
site_author: Gam5510
site_url: https://gam5510.github.io/ITDpy/
repo_name: Gam5510/ITDpy
repo_url: https://github.com/Gam5510/ITDpy

theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Dark mode

    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Light mode

nav:
  - Home: index.md

  - Getting Started:
      - Quickstart: quickstart.md

  - Navigation:
      - Navigation: NAVIGATION.md

  - API:
      - Clans: clans.md
      - Comments: comments.md
      - Discovery: discovery.md  
      - Formatting: formatting.md  
      - Notifications: notifications.md
      - Pins: pins.md
      - Polls: polls.md  
      - Posts: posts.md 
      - Profile: profile.md 
      - Settings: settings.md
      - Upload: upload.md
      - Users: users.md  
  

  - Models:
      - Actor: models/actor.md
      - Comment: models/comment.md  
      - Comments: models/comments.md
      - Discovery: models/discovery.md
      - Notification: models/notification.md
      - Notifications: models/notifications.md
      - Pagination: models/pagination.md
      - Pins: models/pins.md
      - Poll: models/poll.md  
      - Post: models/post.md  
      - Posts: models/posts.md  
      - Settings: models/settings.md
      - Users: models/users.md  